UPLOAD_PATH = 'uploads'
MAX_CONTENT_LENGTH = 1024 * 1024
UPLOAD_EXTENSIONS = ['.csv', '.txt']
SQLALCHEMY_DATABASE_URI = 'sqlite:///../test.db' #PATH TO YOUR DATABASE HERE
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'dev' #YOUR SECRET KEY HERE